name: nodule testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: testing lung nodule
        run: | 
          pip install -r requirements.txt
          python testing.py
          git config --global user.email "mayta51654944@gmail.com"
          git config --global user.name "yantong0116"
          git add . 
          git commit -m "update predict"
          git push
